### ISSUE TITLE
Order price error with PayPal

### ISSUE THREAD

**Issue by michelebenolli** [vendrhub/vendr-payment-provider-paypal#3]
All the orders performed with the PayPal payment provider end up with an error. The problem is related to the order total amount calculated by Vendr at some point in the checkout process. Here are the steps I follow:

1. I put in the cart an item with a price of 1.50€
2. In the checkout process, I choose the PayPal payment provider
3. I complete the payment of 1.50€ with PayPal

At the end of the process, the order has an "Error" status because the amount expected by Vendr for the order is 150€ (1.50 without the decimal separator) and so there are 148.50€ missing. If I choose Stripe as a payment provider, the order is completed correctly without any issue.

**Comment by mattbrailsford** [comment]
Please provide details of what version of Vendr and the PayPal provider you are using

**Comment by michelebenolli** [comment]
Sorry for the duplicate requests in the forum, I posted some requests for other issues and I never received a reply, so I tried here and I asked a colleague with an account with no "limitations" to re-post my questions. I'm using Vendr 1.8.3 and Vendr.PaymentProviders.PayPal v1.1.0, the latest versions.

**Comment by mattbrailsford** [comment]
No problem, can you provide a screenshot of the order details for an order that has gone wrong (please blur anything out that is personal information)?

**Comment by michelebenolli** [comment]
![image](https://user-images.githubusercontent.com/11163189/126345193-ead8dc9c-ff29-494b-8027-60f9cdfcb199.png)
Here the price of the product is 0.82€ with a tax of 22%.

**Comment by mattbrailsford** [comment]
Ok, so from that, given it's the net total that is 82 euro (when it should be 0.82 euro) it would suggest Vendr is at fault, calculating the order value incorrectly.

I'm not quite sure why this would be though as it must have previously been 0.82 in order for PayPal to know to take that amount.

Do you have any custom code that affects pricing? (custom price adjustments etc?)

**Comment by michelebenolli** [comment]
No, I don't have a custom code affecting prices (only a workaround to save a zero price for the product). The amount shown in the PayPal payment page is correct - 0.82€ - and the payment is marked as "complete". May the issue be related to the way in which the response of the webhook is read by Vendr?

**Comment by mattbrailsford** [comment]
I can't think it would be an issue with the webhook. Payment providers only deal with the orders `TransactionAmount` and they only update the `TransactionInfo.AmountAuthorized` and so should not be causing Vendr to re-calculate the order `TotalPrice`

**Comment by mattbrailsford** [comment]
Hmm, actually, maybe it is the webhook as you have actually been given a whopping transaction fee which does come from the payment providers. I wonder if there is a problem here https://github.com/vendrhub/vendr-payment-provider-paypal/blob/dev/src/Vendr.PaymentProviders.PayPal/PayPalCheckoutOneTimePaymentProvider.cs#L191 if PayPal is returning an amount formatted in DKK (using a coma) maybe the decimal.Parse is parsing the coma as a hundred, rather than a decimal.

**Comment by mattbrailsford** [comment]
are you able to pull the source for this payment provider and debug into the webhook handler to see if this is the case? It's a little hard to test formatting issues on a non native computer (ie, it could be down to the servers culture, or just the currency settings)

**Comment by mattbrailsford** [comment]
Actually, I think I might know the issue. I think it's because your machine is DK culture and so `decimal.Parse` will be attempting to parse a string as "0,82" but because it's "0.82" it's getting parsed as "82". I think I just need to update that line to be `decimal.Parse(payPalPayment?.Amount.Value ?? "0.00", CultureInfo.InvariantCulture)`

**Comment by mattbrailsford** [comment]
Ok, there should be a 1.1.1-beta build on the Vendr unstable nuget feed I shared with you previously. If you want to give that a try.

**Comment by michelebenolli** [comment]
My machine is using IT culture but similarly to DK we use comma as decimal separator. I'll try now, thank you.

**Comment by mattbrailsford** [comment]
I think it's definitely the issue. I've run some isolated tests and it looks like it will be the culprit.

**Comment by michelebenolli** [comment]
![image](https://user-images.githubusercontent.com/11163189/126357715-6baf1a21-5a44-45d5-b0c1-c88877b67d12.png)
Issue solved, thank you Matt.

**Comment by mattbrailsford** [comment]
Great stuff. I’ll get a full release out for it tomorrow. Thanks for reporting the issue. 👍🏻

**Comment by mattbrailsford** [comment]
PayPal provider 1.1.1 has now been released with this fix in. Thanks again for reporting 🙏
